### ISSUE TITLE
Roadmap 0.15

### ISSUE THREAD

**Issue by Unitech** [Unitech/PM2#1454]
- [x] Deep inspect SIGSEGV #1380 (remove forcing of gc)
- [x] Inspect weird behaviors #1424 (impact fork and cluster mode) + #1416 + [SO#1](http://stackoverflow.com/questions/31506821/all-my-node-js-apps-crash-unpredictably-at-the-same-time)
- [x] Include simple log rotation into PM2 #1415 #1436 - [waiting for merge](https://github.com/Unitech/PM2/commit/7f894a2593ead41c67ec07fb4494f38022cf1627)
- [x] [Fix node binary path](https://github.com/Unitech/PM2/blob/master/lib/Satan.js#L668)
- [x] More logs message to debug PM2 
- [x] Implement CRON feature in fork mode #1377 
- [x] Add command pm2 deepUpdate (install latest pm2 from npm + update in memory process)
- [x] Fix fork mode with babel #1444
- [ ] Fix NODE_APP_ID after scaling up/down #1332 
- [x] Remove forcing of io.js when running app with --next-gen-js #1444 #1468
- [x] Better error message when syntax error on JSON/JS files #1440 
- [ ] Add option to stop bus streaming of logs
- [x] Add option to disable injection of pmx in fork/cluster mode #1409 #1181 
- [ ] When generating startup scripts we replace HOME_PATH with the home of the root user instead of the current user? (https://github.com/Unitech/PM2/blob/master/lib/CLI.js#L589)

## Optional 

- Output log in JSON format #1318

**Comment by jshkurti** [comment]
deepUpdate  https://github.com/Unitech/PM2/pull/1481 **DONE**

**Comment by jshkurti** [comment]
Add option to disable injection of pmx in fork/cluster mode **[OK]** https://github.com/Unitech/PM2/commit/5faefd2ac8e67f4ca1305b28bcbd35761684efc2

**Comment by jshkurti** [comment]
Implement CRON feature in fork mode **[OK]** https://github.com/Unitech/PM2/commit/0abcae87539b8519dd5c8442f562b3077a7ded64
