### ISSUE TITLE
PM2 Roadmap

### ISSUE THREAD

**Issue by jshkurti** [Unitech/PM2#1554]
- [ ] Feature : Implement a proper watchdog for PM2 (instead of the watchdog being in the Keymetrics Agent) #1540
- [x] Issue : Dumpfile being empty after reboot #1035 (fix: `chown` the ~/.pm2 folder)
- [ ] Enhancement : `pm2 resurrect` should not restart apps being in STOPPED status but leave them stopped instead #1503
- [ ] Issue : NODE_APP_INSTANCE doesn't work well with `pm2 scale`, the values are wrong after a scale being applied #1332
- [ ] Enhancement : Evaluate JSON declaration on every command instead of only `pm2 start` #1502 #1366
- [ ] Enhancement : `pm2 scale` down should gracefully stop apps instead of killing them #1346
- [ ] Feature : `pm2 gracefulStop` command #1286

**Comment by artursudnik** [comment]
in my installation.pm2 folder is owned by user but still after reboot appliction is not started

This is what is written to pm2.log file during system restat. I am not sure if this should be alarming but it seems that pm2 is restarted twice.  The second time there are no applications running so this is when empty dump.pm2 file is created.

2015-09-10 00:06:55: pm2 has been killed by signal, dumping process list before exit...
2015-09-10 00:06:56: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-10 00:06:56: [[[[ PM2/God daemon launched ]]]]
2015-09-10 00:06:56: BUS system [READY] on port /home/artur/.pm2/pub.sock
2015-09-10 00:06:56: RPC interface [READY] on port /home/artur/.pm2/rpc.sock
2015-09-10 00:06:57: PM2 is being killed via kill method
2015-09-10 00:06:57: RPC socket closed
2015-09-10 00:06:57: PUB socket closed
2015-09-10 00:07:08: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-10 00:07:08: [[[[ PM2/God daemon launched ]]]]
2015-09-10 00:07:08: BUS system [READY] on port /home/artur/.pm2/pub.sock
2015-09-10 00:07:08: RPC interface [READY] on port /home/artur/.pm2/rpc.sock

**Comment by hypesystem** [comment]
What happened to this roadmap, why was it closed? Specifically, #1286 would be direly needed.

**Comment by rubennorte** [comment]
I'm also very interested in #1366.
