### ISSUE TITLE
Enhancements for 1.2

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2176]
Install development version:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

## Features

- [x] #2203 Deep CLI refactor
- [x] allow module to have descriptions (json desription via pm2 show + after installation)
- [x] [https://github.com/Unitech/pm2/commit/2db2e6734111647e5ae226437ec391dd7ada2f82] Githuib issues template
- [x] [https://github.com/Unitech/pm2/commit/20344a58f19e57a8dc8f4e7e1ed1f9afc29473ea] [https://github.com/Unitech/pm2/commit/610d68f8d7768d3880fec04dc6cdd3191fd4004f] [https://github.com/Unitech/pm2/commit/7783c15507cb3c99343144cfbbc76e0296edaee4] Reduce memory of 10mb by removing any Satan require in Daemon
- [ ] #2105 alias pm2 log with pm2 logs (bug with commander)
- [ ] #2142 pm2 restart <app> --default? 
- [ ] #2090 interactive prompt
- [x] #1979 [https://github.com/Unitech/pm2/commit/4f810a1e381baa5fcc868bfcc7b266bd04b8eb3a] [https://github.com/Unitech/pm2/commit/2746c3861fe826e7e3f09627a5c1af6d82c73889] [https://github.com/Unitech/pm2/commit/618862fb4e0fa2e856c4013a477a2bd32c5d4cc1] enhance module system 
- [x] #2069 [https://github.com/Unitech/pm2/commit/5919ca61265f01ad78361c91524689a7faf4cfc9] Add deprecation message for gracefulReload
- [ ] #2175 create a light PM2 API client (++custom SOCK files, env cloning, env trim)
- [x] [https://github.com/Unitech/pm2/commit/bcf1acd85e1d0f06b5ce7602e2928140293a6377] upgrade PMX internals (smart algorithm fix, unref for event loop, copy path...)
- [x] [https://github.com/Unitech/pm2/commit/618862fb4e0fa2e856c4013a477a2bd32c5d4cc1] enhance visuals when installing pm2 module (check interactive, ora)
- [x] review pm2-deploy PR
- [ ] deep restart (https://github.com/Unitech/pm2/commit/1efa1869ac317f9714e9eb186c4ed5f0614c4ddc)
- [x] [https://github.com/Unitech/pm2/commit/bcf1acd85e1d0f06b5ce7602e2928140293a6377] pm2 start npm -- start (eq npm start) now fully supported with auto restarts
- [ ] bundle all dependencies into PM2 NPM module for faster install (++fix [modclean](https://www.npmjs.com/package/modclean) path problems)
- [ ] custom filepath for saving dump files: pm2 save [filename.json]
- [x] [https://github.com/Unitech/pm2/commit/c4da9d3ff245446c17351dc8a156f5a64c984a64] upgrade to cli-table-2
- [x] [https://github.com/Unitech/pm2/commit/66a8b59b4d210b48ebae48152b6af8cd0fee0a0b] pm2 ls --watch (via [clear](https://www.npmjs.com/package/clear))

## [pm2-deploy](https://github.com/Unitech/pm2-deploy) merged PR

[https://github.com/Unitech/pm2-deploy/pull/91] fix: Fixed a bug if package path contains spaces
[https://github.com/Unitech/pm2-deploy/pull/81] fix: tilde expansion of key
[https://github.com/Unitech/pm2-deploy/pull/87] fix: fix Broken relative path handling causes "deploy log append failed"
[https://github.com/Unitech/pm2-deploy/pull/79] feature: added pre-setup and post-setup hooks
[https://github.com/Unitech/pm2-deploy/pull/92] feature: fetch all tags from the remote
[https://github.com/Unitech/pm2-deploy/pull/32] feature: deploy [json] [environ] list -- show each commit with prefix of revert n
[https://github.com/Unitech/pm2-deploy/pull/89] feature: allow to pass ssh options

## Bugs

- [ ] #2154 Cannot read property pm2_env of undefined
- [x] #2133 #2077 Env trimming (pm2 goes to infinite restart...) or fix via light PM2 API
- [ ] #2064 'Start' command fails with more than 4 options on --arg option

**Comment by geuis** [comment]
This is installing 1.1.3, not 1.2.

> $ npm install Unitech/pm2 -g
> $ pm2 update

Trying to use this

> pm2 start npm -- start (eq npm start) now fully supported with auto restarts

**Comment by Unitech** [comment]
Exact, I forgot to add `#development`, fixed :)

**Comment by Unitech** [comment]
## [pm2-deploy](https://github.com/Unitech/pm2-deploy) merged PR

[#91] fix: Fixed a bug if package path contains spaces
[#81] fix: tilde expansion of key
[#87] fix: fix Broken relative path handling causes "deploy log append failed"
[#79] feature: added pre-setup and post-setup hooks
[#92] feature: fetch all tags from the remote
[#32] feature: deploy [json] [environ] list -- show each commit with prefix of revert n

**Comment by Unitech** [comment]
#2289
