### ISSUE TITLE
Docker integration: Development / Distribution mode

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2320]
The goal is to easily **start an application into a Docker container** under two modes: _Development Mode_ (Watch file & Restart, Application mounted as a Volume, inner NPM install) and _Distribution Mode_ (source COPY, right ENV variables, right process manager).

This will allow to have an immutable system for all environments (dev, test, staging, prod) while keeping a test-edit-reload cycle short in Development mode and consistent Distribution mode for other environments.
## Development mode

In Development mode your current working directory will be exposed as a Volume into Docker, allowing to edit files on your host machine and in case of file change the pm2 runtime (the one inside the container) will restart your application. The `host` network-bridge will be used to bind the exact same port being used in your container in the host machine.

``` bash
$ pm2 docker:dev [process.yml|app.js]
```

Under the hood this command first generate a Dockerfile (CWD, started file...) then build it and run it.
## Distribution mode

Once you want to deploy your application, you can now switch this container to **Distribution mode**. Distribution mode means that your application source will be copied into the container and the pm2 runtime will be switched to production mode.

``` bash
$ pm2 docker:dist [process.yml|app.js] "image/name"
```

The container will start, then do 'Ctrl-C', it will prompt about pushing/committing the new container
## Demo

Wrapping an application into a Docker container and run it:
[![asciicast](https://asciinema.org/a/2dahreqvxhlar47zh7g0jd3h2.png)](https://asciinema.org/a/2dahreqvxhlar47zh7g0jd3h2)
## Roadmap
- [x] check Docker rights
- [x] pm2 docker:wrap app.json || pm2 docker:distribute
- [x] State file (allow switching directives in Dockerfile without deleting user custom instructions)
- [ ] pm2-deploy for docker container
- [ ] pm2 start process.yml --container
- [ ] pm2 install (docker pull) with probes pre-conf
### Development generation steps

Steps:
- If no Dockerfile is present generate one ([template](https://gist.github.com/Unitech/1448f9c879038fe86d9acf3c52a6487a) then [final](https://gist.github.com/Unitech/860553d1e8adb7b04bb6e2db14863693))
- Build this Dockerfile via command `docker build -t [name] -f [Dockerfile path] .`
- Run container via command `docker run --net host -v pwd:/var/app [name]`

**Comment by Unitech** [comment]
Make use of:
- Docker image with source mounted as a volume: https://github.com/pm2-hive/docker-volume
- Monitoring probe running inside container https://github.com/pm2-hive/pm2-docker

**Comment by Unitech** [comment]
Asciinema for pm2 docker:dev app.json

[![asciicast](https://asciinema.org/a/2dahreqvxhlar47zh7g0jd3h2.png)](https://asciinema.org/a/2dahreqvxhlar47zh7g0jd3h2)
