### ISSUE TITLE
Roadmap to 0.8.x

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#376]
- [x] Watch feature #368 #375 
- [x] No color output #358
- [x] Systemd startup scripts #333 
- [x] Only JSON output #281 
- [x] New documentation
- [x] Dump at regular interval
- [x] Log aggregation #365 #344 #337
- [x] Disp all returned "errors" in pm2.log
- [x] Use Axon in UNIX mode (https://github.com/visionmedia/axon#binding--connecting)
  - [x] Update Axon RPC + PR
