### ISSUE TITLE
66road

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#47]
- [x] Delete pid files when processes stopped #44 
- [ ] Rename stopAll to stop-all or stop all (but still keep restartAll and stopAll for compatibility) #44 
- [ ] V8 Options #45 
- [ ] Stop web server #42 
- [ ] Review merge web interface #36
