### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#810]
- [x] Worker system for CRON restart and MAX-MEMORY-USED [#742][#697]
- [x] Append date to pm2.log [#764]
- [x] gracefulStop/gracefulRestart CLI methods [#478]
- [ ] Multiple calls to resurrect shouldn't start the processes again [#300]
- [x] Reload should update environment variable as restart do (CLI.js l979)
- [ ] Delay option between restart [#498]
- [x] `--combine-logs` to merge stderr and stdout [#807]
- [x] Double check PID deletion on process exit [#797]
- [x] startOrRestart / startOrReload fixes [#805][#724][#695][[#678]
- [x] Double check `max_restarts` option [#718]
- [x] CRON restart in Worker [#662]
- [x] Action on multiple processes - (e.g.) pm2 delete 1 2 3 4
- [x] Custom path for dump files pm2 save . ; pm2 resurrect .
- [x] Smart restart (pm2 start <app_name_already_started> == pm2 restart)
- [x] Alias pm2 info by pm2 show

Follow new features and bug fix: https://github.com/Unitech/PM2/blob/development/doc/CHANGELOG.md#0122

**Comment by murphyj** [comment]
Hey @Unitech great to see these features are on the slate.

I'm guessing that's why when I do the following it doesn't work. I have a file called crontest.js:

```
ar pm2 = require('pm2');

console.log("Pm2 Cron is running me...");


pm2.connect(function() {
    pm2.stop('crontest');
});
```
What I essentially want to do is start a process off the first time the app is loaded and then kick the process off every X minutes using the --cron option.

So first cmd would be:
```
pm2 start crontest.js
```
Followed by
```
pm2 restart crontest --cron "*/1 * * * *"
```

My understanding is that the restart command will kick the pm2 job off every 10 minutes on the hour e.g. 1pm, 1.10pm, 1.20pm etc...

I'm guessing i'm waiting for 
CRON restart in Worker
and
Smart restart (pm2 start == pm2 restart)

**Comment by murphyj** [comment]
Ah looks like we can run it in cluster mode but not fork mode - guess we'll just have to make a note of that for dev environment if we need to test it - thanks!

Great notes by the way.

**Comment by Unitech** [comment]
All things implemented/fixed, closing
